# Generated by Django 6.1.1 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número/Nome')),
                ('status', models.BooleanField(default=False, verbose_name='Status da Sala')),
            ],
        ),
    ]
