# Generated by Django 6.1.1 on 2026-09-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sala',
            new_name='Salas',
        ),
    ]
