# Generated by Django 6.1.1 on 2026-09-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_rename_sala_salas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salas',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
    ]
